#!/usr/bin/env python

import HTMLParser
import requests
from urllib import urlopen
import urlparse
from sys import argv, exit
from os.path import basename, dirname, exists
from getopt import getopt

class LinkTester(HTMLParser.HTMLParser):

    ### Overridden methods

    def __init__(self,verbose=False):

        HTMLParser.HTMLParser.__init__(self)
        self.verbose=verbose
        self.cache={}
        self.dirname=""
        self.filename=""
        self.lineno=0

    def feed(self,lineno,line):

        # Keep track of the line number to enable better output
        self.lineno=lineno
        HTMLParser.HTMLParser.feed(self,line)

    def handle_starttag(self, tag, attrs):

        # Test the linked to URL and print the appropriate output
        if tag == "a":
            for attribute, value in attrs:
                if attribute == "href":
                    url = value
                    break
            self.output_testing(url)
            if self.test_link(url):
                self.output_okay()
            else:
                self.output_broken(url)

    ### Substantial new methods

    def test_link(self,link):

        """Return True if link is okay, False if link is broken."""

        # Have we already checked this link?
        if link in self.cache:
            return self.cache[link]

        # Determine what kind of link we're dealing with
        # and dispatch the testing accordingly.

        if link.startswith("/"):
            result = self.test_relative_link(link)
        elif link.startswith("#"):
            result = self.test_internal_link(link)
        elif link.startswith("mailto"):
            result = self.test_mail_link(link)
        else:
            result = self.test_absolute_link(link)

        # Cache the result incase this link comes up again
        self.cache[link]=result

        return result
    
    def test_internal_link(self, href):

        """Test a link to a "name"ed or id"ed" tag in this document."""

        return True    # Not yet implemented, shouldn't be too hard

    def test_mail_link(self, href):
    
        """Test a mailto: link"""    # No idea if this is possible

        return True

    def test_relative_link(self, href):

        """Test a relative link (i.e. to a file in this directory)."""

        if self.seed.startswith("http://"):
            url = self.urlparsed.scheme + "://" + self.urlparsed.netloc + href
        return self.test_absolute_link(url)

    def test_absolute_link(self, url):

        """Test an absolute link."""
        response = requests.head(url)
        return response.status_code == 200

    ### Insubstantial new methods

    def output_testing(self,url):

        """Notify the user we are testing a link."""

        if self.verbose:
            print "%s:%d Testing \"%s\"..." % (self.filename,
                self.lineno, url),

    def output_okay(self):

        """Notify the user a link tested okay."""

        if self.verbose:
            print "OK!"

    def output_broken(self,url):

        """Notify the user a link tested as broken."""
        
        if self.verbose:
            print "BROKEN! <==---"
        else:
            print "%s:%d \"%s\" is broken!" % (self.filename,
                self.lineno,url)

### Fairly standard functions to facilitate command line use

def usage():

    print "TestLinks 0.1"
    print "Copyright Luke Maurits, 2007"
    print "See http://www.luke.maurits/software/testlinks/ for latest version"
    print ""
    print "usage: testlinks [-s] [-h] file1 file2 file3..."
    print "-h prints this usage message."
    print "-s specifies 'silent mode': no output if no broken links are found."

def main():

    verbose = True

    try:
        options, files = getopt(argv[1:],"hs")
    except GetoptError:
        print "Unrecognised option!"
        usage()
        exit(2)

    if not files:
        usage()
        exit(2)
    
    for (o,a) in options:
        if o=="-s":
            verbose=False
        if o=="-h":
            usage()
            exit(0)

    tester = LinkTester(verbose)
    for filename in files:
        tester.seed = filename
        if filename.startswith("http://"):
            tester.urlparsed = urlparse.urlparse(filename)
        try:
            fp=urlopen(filename)
        except IOError:
            print "Could not open page %s!" % filename
            continue 
        tester.dirname=dirname(filename)
        tester.filename=basename(filename)
        try:
            for line_number, line in enumerate(fp):
                tester.feed(line_number+1,line)
        except HTMLParser.HTMLParseError:
            print "Error parsing page %s: is this an (X)HTML document?"
        fp.close()
    exit(0)

if __name__=="__main__":
    main()
